### ISSUE TITLE
Compatibility to netbox 2.9

### ISSUE THREAD

**Issue by doiiido** [lopes/netbox-scanner#20] opened 2020-08-28 19:08 UTC
I´ve been trying to integrate into a fresh install of netbox 2.9.2, but it seems that the API has changed a bit.
This is the error I keep getting on trying to use nmap functionalities, both in the pre-2.0 versions and the actual netbox-scanner:
"
Traceback (most recent call last):
  File "netbox-scanner/nbscanner", line 75, in <module>
    nbs.sync(networks)
  File "/opt/netbox-scanner/netbox-scanner/nbscanner.py", line 228, in sync
    self.sync_network(network)
  File "/opt/netbox-scanner/netbox-scanner/nbscanner.py", line 157, in sync_netw                                                                                        ork
    self.sync_host(host)
  File "/opt/netbox-scanner/netbox-scanner/nbscanner.py", line 144, in sync_host
    tags=[self.tag], description=host[1])
  File "/usr/local/lib/python3.6/dist-packages/pynetbox/core/endpoint.py", line                                                                                         279, in create
    ).post(args[0] if args else kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pynetbox/core/query.py", line 295                                                                                        , in post
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request:                                                                                         {'tags': [['Related objects must be referenced by numeric ID or by dictionary of                                                                                         attributes. Received an unrecognized value: auto']]}
"
The actual version of netbox-scannet passes nmap value instead of auto.
Maybe an update of the pynetbox to the current version may fix the issue.
Best Regards,
Lincoln

**Comment by lopes** [comment] 2020-08-28 19:32
Makes sense.
I did use pynetbox v4.3.1 and the current version is 5.0.7, a major update.
You could give it a try and report me back if it works, preferably sending a PR --run the tests to make sure nothing was broken.

**Comment by doiiido** [comment] 2020-08-28 19:49
Not related to pynetbox, same error still on 5.0.7

**Comment by lopes** [comment] 2020-08-28 20:09
I noticed you're running an old version of netbox-scanner (`nbscanner.py` no longer exists).
You could try to upgrade to v2 but notice that Nmap scans must be run apart from netbox-scanner, see README.

**Comment by doiiido** [comment] 2020-08-28 21:15
I´ve tested both versions, the issue is reproduced in both.
Can´t test the 5.0.7 version now due to SSL issues, the SSL verify flag has been taken out, I managed to refactor enough so the code would work, but my netbox hasn´t a valid SSL certificate.

**Comment by lopes** [comment] 2020-08-28 21:50
I see.
If the `ssl_verify` option was deprecated, guess they'll have to give us an alternative, because most environments use internal certificates.
If NetBox v2.9 is not compatible with pynetbox v4, guess there's no way out. I could not reproduce this error here (using NB v2.6).

**Comment by doiiido** [comment] 2020-08-29 14:57
Seems like there might be an answer...
This is a extensive documentation for pynetbox, sharing this because was getting hard to find a complete one:
https://buildmedia.readthedocs.org/media/pdf/pynetbox/latest/pynetbox.pdf

**Comment by doiiido** [comment] 2020-08-29 15:04
The flag has been moved, It's accessible at 
netbox.http_session.verify = False
where netbox is the API object of pynetbox

**Comment by doiiido** [comment] 2020-08-29 15:05
the issue is still present on 5.0.7

**Comment by doiiido** [comment] 2020-08-29 16:39
Got it.
The issue is related to the fact that tags are an object and need to be created separately...

**Comment by lopes** [comment] 2020-08-31 12:17
Looks like you've been busy over the weekend. :)
If tags must be referred by their IDs, a subroutine must be implemented to get the ID for the tag set in the config file, then use this ID in the writing process.
But it breaks the compatibility with older versions, like mine and many others. It's a hard decision to take.

**Comment by doiiido** [comment] 2020-08-31 12:31
Hi,
I'm using pynetbox 5.0.7 and netbox 2.9.2, I've modified the flag SSL
verify and modified the create part so it would reference the tag by ID.
The tests related to netbox did pass but the delete part for nmap is still
broken.
Didn't test other parts (prime or netxms).

Best Regards,
Lincoln.

Em sex, 28 de ago de 2020 16:32, José Lopes <notifications@github.com>
escreveu:

**Comment by theOrakle** [comment] 2020-09-08 01:37
What did you do to fix this?

**Comment by timlee90** [comment] 2020-10-08 09:36
@doiiido, any pointers for a newbie?
I upgraded our Netbox environment yesterday and thought I'd give this a go but I'm having the same issue.
What do I need to edit and where?  

Looking forward to any feedback, I would be extremely grateful for any assistance provided.

**Comment by ndom91** [comment] 2020-11-15 19:27
If you don't mind it not adding the tag of the module it used to scan / add the IP, you can remove line 50 in `nbs/__init__.py` so that

```
self.netbox.ipam.ip_addresses.create(
    address=host[0],
    tags=[self.tag],
    description=host[1]
)
```
Becomes
```
self.netbox.ipam.ip_addresses.create(
    address=host[0],
    description=host[1]
)
```

**Comment by timlee90** [comment] 2020-11-16 09:30
> If you don't mind it not adding the tag of the module it used to scan / add the IP, you can remove line 50 in `nbs/__init__.py` so that..
> 
> ```
> self.netbox.ipam.ip_addresses.create(
>     address=host[0],
>     tags=[self.tag],
>     description=host[1]
> )
> ```
> 
> Becomes
> 
> ```
> self.netbox.ipam.ip_addresses.create(
>     address=host[0],
>     description=host[1]
> )
> ```
> 
> That'll remove the need for the subroutine to grab the ID of a potential 'nmap' (or whatever module) tag to insert here.
> 
> Btw @lopes - they recently changed the tag system in netbox a bit where you cannot create tags on the fly anymore when adding one to a device. You have to explicitly go into tags first (in the UI as well as the API i'm assuming) and create the tag, and then and only then will you be able to apply it to devices.

ndom91, thank you so so much for this. I will lab today and give it a go. 

Many thanks!

**Comment by ndom91** [comment] 2020-11-16 09:55
No problem, let me know if you have any other problems. I remember I had to adjust a few things to get this working with the new(er) version (I'm on 2.9.8) of Netbox

**Comment by lopes** [comment] 2020-11-16 11:57
@timlee90 I'm aware this tag system has changed, but I'm unable to work on this right now and my environment is still using an older NetBox version. As far as I know, from now on it will be needed to create a tag and get its ID (or retrieve the ID of an existing tag) and then use this ID to associate with the new object. It's not hard but requires an extra step.

**Comment by lopes** [comment] 2020-11-16 17:21
Since @ndom91 sent a pull request to fix this issue, I'm going to close this thread. Note that tagging is not supported yet, so we still need the routines to create new tags and lookup for tag IDs.
Thanks!

**Closed by lopes** 2020-11-16 17:21 UTC
Labels: dependencies
